### ISSUE TITLE
Info updated instantly, rather than when played (Serato)

### ISSUE THREAD

**Issue by speedyb22** [whatsnowplaying/whats-now-playing#185]
Using Serato Pro 2.5.5 on Windows, both 2.x and 3.x change the track name as soon as it's loaded, when using the "newest" option; I could amend the delay, but the current track could be quite long, and I may know what I want to play next, so a delay will still show the incorrect track on screen for a while.

I use a 4 deck controller, and often keep scratch samples loaded into decks 3 and 4, so using the "oldest" option keeps showing the filename for this instead.

Version 1.4.0 only updates the track name when the song is actually playing. If I load two tracks and set them both playing at the same time, but the volume fader is down on deck 2, the track will not update until it's faded in and actually playing out.

**Comment by aw-was-here** [comment]
Thank you for the bug report! Great use case!

I'll see what I can do to fix the issue.  I was debating adding the ability to actually mark decks as 'ignorable' so that they don't even participate in the calculation. (e.g, in your case, if you wanted to swap out your scratch samples, that would _also_ disrupt things too). This bug might just make me do that since that might be the fastest way to fix it.  The fact that 1.4.0 works is sort of interesting, given I was seeing other issues with how that version was parsing the session file.

Just to give a bit of a warning, it might take me a bit to get real fix in place since I'm going to be out of town for most of the next month.

**Comment by speedyb22** [comment]
Ignored deck(s) would be useful, I pretty much use 3 and 4 for samples only.

The way 1.4 works would probably be my 'expected' behaviour for update timing, given it only updates once the track is actually playing out. Before now I've loaded in 4 or 5 tracks before settling on which one is actually going to play next. Though, ignored decks combined with the 'older' setting could be a workaround for now.

I rarely use the Live Playlists feature in Serato, but I've just tried it and it works in a similar manner, no updates until the volume (or crossfader) is moved onto the new track, not sure if that's any use for the local mode at all, just an interesting observation. 

Absolutely no worries about timing, the changes thus far - both implemented and planned - are fantastic!

**Comment by aw-was-here** [comment]
PS, haven't forgotten. Waiting for the arrival of a 4-deck controller that I bought off of eBay (but that is having issues. probably getting scammed).

**Comment by speedyb22** [comment]
No problem, hopefully it's not a scam, or at the very least eBay can sort things out swiftly. 

If there's any logs/data/information I can provide in the meantime, let me know, and I'll see what I can do.

**Comment by aw-was-here** [comment]
eBay refunded me. Sooo... in order to make some progress on this, I'm going to implement the ability to ignore decks 1-4.
