### ISSUE TITLE
Song is not updating until the app is restarted

### ISSUE THREAD

**Issue by djquartz** [whatsnowplaying/whats-now-playing#306]
I'm using the webserver option and everything is talking but it seems the app is stalling and not updating until I restart the app and then I see the song update in obs via the browser control.

I'm not sure what's causing it to stall but it does pull the information which is strange.

**Comment by djquartz** [comment]
Just to add further details after further testing.

It seems to be an issue with the local Serato function vs the web feed. The web feed is working nicely after testing but the local option doesn't update the song information correctly.

**Comment by aw-was-here** [comment]
I really need to get a template in place. :)

Is this 3.0.0 RC8?  Is it set for newest or oldest?  How many decks?

On the restart, does it update once and then never updates again or it updates continuously (e.g., restart -> new track -> update -> new track -> update -> ...)

**Comment by djquartz** [comment]
This is my config for the local function

Version 3.0.0 RC8
Webserver Option
2 decks (1 & 2)
Newest
On restart it will update then stop, restart again, same result
The _Serato_ folder is accessed via unc path

Only the local function behaves in this manner, the remote option is working well.

**Comment by aw-was-here** [comment]
OK that means the thread that is supposed to watch for Serato updating its external files isn't working or for some reason Now Playing is rejecting what it is reading.  By chance, do you have your Serato folder on an external drive?   I have a hypothesis....

**Comment by djquartz** [comment]
The Serato folder is on an internal drive, same drive Serato DJ is installed on.

However, I have a secondary internal where all my music/videos are stored.

However, I'm running it on a Macbook connected to the network. My studio PC is running the What's Playing now on Windows 10.

**Comment by aw-was-here** [comment]
Ah... I think I'm getting the picture now. It sounds like there is a network mount in the middle (either Windows is mounting the Mac drive or the Mac is mounting the Windows drive).  That's ... going to make things difficult.  

I think the way forward here is Now Playing needs to provide a way to go back to the less efficient file change detection method that was in place in earlier builds where it would scan the file system rather than wait for the operating system to say something changed.  It'll use up some CPU and things will be slightly slower but that is better than completely broken.  By making it an option, people can pick which method works for them.

Thanks for the report!

**Comment by djquartz** [comment]
Yeah I'm accessing the _Serato_ folder on the Mac from the Win10 machine via unc path.

I tried it with a mapped drive and it didn't work at all.

Sounds good, and no problem!

**Comment by aw-was-here** [comment]
An interesting experiment would be to run Now Playing on the Mac.  It _should_ update like it is supposed to.  If that does work, then at a minimum there needs to be a documentation update to call out that local mode runs on the same machine as the Serato folder rather than 'just Serato'.  I'll be honest, this scenario is not one I had considered!  :smile:

**Comment by djquartz** [comment]
It could be my interpretations as well.  OBS runs on the Win10 system which is my Studio PC that houses everything for production. So when the reference for localhost.... for the browser object was the setting I was like hey. I don't have to worry about ip's changing on the network.

That's why I implemented it this way. I though hey I can use local mode and take the website out of the equation by accessing the Serato folder via unc in Now Playing, voila.

**Comment by djquartz** [comment]
Just to add context, the Win10 system houses everything. The Macbook runs all the DJ applications such as Serato, SoundSwitch, and MixEmergency.

**Comment by aw-was-here** [comment]
Yeah, the expectation is that NowPlaying is running on the same machine as Serato's folder which of course means you'd need to mess around with hostnames/ip addresses in OBS then.  But your scenario is totally doable by enabling the older 'scan the filesystem' behavior so long as 'weird' things don't happen over the network path.  I think that's a worthwhile toggle to implement since there may be other cases where it isn't possible to run on the actual machine and/or the OS isn't getting filesystem events correctly.

**Comment by djquartz** [comment]
Ok, once it's implemented I will give it shot and test the local functionality vs the remote.

**Comment by aw-was-here** [comment]
It just occurred to me that I will also need to implement a file path translation hook.  The binary Serato session files will point to the path as seen on the Mac.  On the Windows side, it won't know how to read that file because it will live in a different place.  If one doesn't need to read the raw files (e.g., for covers, album name, and other song metadata), that isn't that big of deal but then people wouldn't be using Now Playing if they just wanted title and artist. :laughing:

**Comment by djquartz** [comment]
Ahhh yes,

Would it be easier if the drive was mapped vs unc path?

**Comment by aw-was-here** [comment]
Not really.  I'm going to add a 'Quirks' option in the settings and put both 'file remapping' and 'scan for changes' there. Both of these are applicable for non-Serato users too...  It's going to be a bit before I get chance to bang that code out, FYI.

**Comment by djquartz** [comment]
No problem, I'm using the remote option which is working perfectly for the time being. I was just thinking if someone wants to avoid pushing data to the serato site and then pulling it back down again... they could with the local option.

**Comment by aw-was-here** [comment]
Yup. Totally agree. I'm not a fan of that feature of Serato's either. :+1:

**Comment by djquartz** [comment]
I like it for Mixcloud content with the upload feature after my set is done. I'm glad it's there because I wouldn't be able to use this great add-on without it currently.

**Comment by aw-was-here** [comment]
OK, this should be fixed in rc9 by enabling the 'poll' option in Quirks.  Also, you might need to play around with file renaming if you want to use enhanced tags, etc, etc.

**Comment by aw-was-here** [comment]
FYI: #331 will make this easier to use
